### PR TITLE
Updating plugin marketplace URL

### PR DESCRIPTION
**Pull request by gtaylor**
Minor but potentially confusing to new devs. I don't think the old URL is being updated anymore.

### CODE REVIEW

**Comment by tboerger** [comment]
Is this repo still used? The currently listed plugins are already official plugins

**Comment by tboerger** [comment]
Beside the above comment LGTM

**Comment by jackspirou** [comment]
LGTM.  I'll merge but if we have a separate source of truth we should use that.  @gtaylor please advise :)

**Comment by jackspirou** [comment]
LGTM

**Pull request merged**
